sudo: false
language: minimal

addons:
  apt:
    packages:
    - pandoc

script:
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s --
    - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.2

branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
